### ISSUE TITLE
[Feature Request] Don't re-fold things that are manually unfolded

### ISSUE THREAD

**Issue by forivall** [levi-pires/auto-fold-unfold#1]
Current behaviour: after manually unfolding something, and then moving the cursor, it gets re-folded
Desired behaviour (with option?): after manually unfolding something, it shouldn't be automatically re-folded. At least until after the text inside the fold region is edited, perhaps.

**Comment by forivall** [comment]
Also, if this is something you'd be open to merge, i'd be open to submit a PR for this (i've [previously worked on editor extensions around folding](https://github.com/forivall/atom-remember-folds))

**Comment by levi-pires** [comment]
I'm glad to receive your review.  I will work on it as soon as possible.  feel free to open a pull request

**Comment by levi-pires** [comment]
you can use the commands to freeze the extension, so it just unfolds

[Commands](https://github.com/levi-pires/auto-fold-unfold#commands)

**Comment by forivall** [comment]
Yeah, i looked through your code and vscode's extension capabilities, and i don't see an obvious way to read what the current folding ranges are -- and you're just using the existing commands, i was hoping it was something more complex (no fault to you, don't worry. So i'll just submit a PR to the extension add an option to make the default mode "freeze", and then have to toggle the freeze option to enable the auto folding.

**Comment by levi-pires** [comment]
I'm sorry but this extension will no longer be maintained.  Feel free to clone the repository if you want
